# Generated by Django 4.1.7 on 2023-03-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0002_rename_post_adv_rename_date_post_adv_date_adv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='content',
            field=models.FileField(null=True, upload_to='content'),
        ),
        migrations.AddField(
            model_name='adv',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
