# Generated by Django 4.1.7 on 2023-03-16 12:24

import adv_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0004_alter_adv_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adv',
            name='content',
        ),
        migrations.RemoveField(
            model_name='adv',
            name='image',
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(null=True, upload_to=adv_app.models.author_directory_path)),
                ('adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adv_app.adv')),
            ],
        ),
    ]
