# Generated by Django 4.1.7 on 2023-03-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0005_remove_adv_content_remove_adv_image_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='adv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='adv_app.adv'),
        ),
    ]
