# Generated by Django 4.1.7 on 2023-03-17 15:56

import adv_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0006_alter_media_adv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='content',
            field=models.ImageField(null=True, upload_to=adv_app.models.author_directory_path),
        ),
    ]
