# Generated by Django 4.1.7 on 2023-03-18 13:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0007_alter_media_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='text_adv',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
