# Generated by Django 4.1.7 on 2023-03-19 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adv_app', '0008_alter_adv_text_adv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='adv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='adv_app.adv'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to=settings.AUTH_USER_MODEL),
        ),
    ]
