# Generated by Django 4.1.7 on 2023-03-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0010_rename_user_reply_reply_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='adv',
            new_name='adv_reply',
        ),
    ]
