# Generated by Django 4.1.7 on 2023-03-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0011_rename_adv_reply_adv_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='adv_reply',
            new_name='adv',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_author',
            new_name='author',
        ),
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Видимость'),
        ),
    ]
