# Generated by Django 4.1.7 on 2023-03-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0012_rename_adv_reply_reply_adv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeActivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('code', models.CharField(blank=True, default=None, max_length=6, null=True)),
            ],
        ),
    ]
