# Generated by Django 4.1.7 on 2023-03-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0013_codeactivate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeActivate',
        ),
    ]
