# Generated by Django 4.1.7 on 2023-03-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0015_codeactivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authoruser', to='adv_app.author'),
        ),
    ]
