# Generated by Django 4.1.7 on 2023-03-26 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adv_app', '0016_alter_adv_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authoruser', to=settings.AUTH_USER_MODEL),
        ),
    ]
