# Generated by Django 4.1.7 on 2023-03-26 16:39

import adv_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0017_alter_adv_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='content',
            field=models.ImageField(null=True, upload_to=adv_app.models.author_directory_path),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
