# Generated by Django 4.1.7 on 2023-03-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0021_alter_adv_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
