# Generated by Django 4.1.7 on 2023-03-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv_app', '0023_alter_adv_category_name_alter_adv_head_adv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
